- name: Install dependencies
  apt:
    name: ['unzip']
    state: latest
    update_cache: yes
  become: true

- name: download and install terraform
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_amd64.zip"
    dest: "/usr/local/bin"
    remote_src: yes
    mode: "755"
    owner: root
    group: root

- name: download helm
  become: true
  unarchive:
    src: "https://get.helm.sh/helm-v3.5.1-linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
    mode: "755"
    owner: root
    group: root

- name: move helm binary
  become: true
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    owner: root
    group: root
    mode: 0755

- name: Remove terraform tfstate file
  become: true
  file:
    path: /vagrant/terraform/terraform.tfstate
    state: absent

- name: Provision infra
  become: true
  terraform:
    project_path: "/vagrant/terraform"
    state: present
    force_init: yes


