---
- name: Stop and disable systemd-resolved
  become: true
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Configure Google DNS server
  become: true
  copy:
    src: google_resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'



